### ISSUE TITLE
`fn score` panics if query char not in search string

### ISSUE THREAD

**Issue by arminfriedl** [jcs090218/flx-rs#1]
A simple query like

```rust
#[test]
fn test() { score("Test", "d"); }
```
panics in `find_best_match` when trying to find "d" in `str_info`.

```rust
#[test]
fn test() { score("Testd", "d"); }
```
works since then `str_info` built from the search string contains the query string char(s).

Seems like a pretty straight forward bug. But I didn't really dig enough into the code to know what the right fix would be.

**Comment by jcs090218** [comment]
Thanks for reporting this issue! 👍 

I have applied a fix in 1fb9d4049df66e76270e8d5d3c97772fd874f052.
