### ISSUE TITLE
Different scores between implementations

### ISSUE THREAD

**Issue by jojojames** [jcs090218/flx-rs#6]
(flx-score
 "~/.emacs.d/straight/repos/orderless/orderless.el" "odrless")
(222 26 28 30 31 32 33 34)

(flx-score
 "Code/Everyone/Xamarin/EMJavaBindings/EMJavaBindings/Additions/DrawableSoftReference.cs"
 "odrless")
(138 1 62 63 68 69 70 85)

(flx-rs-score
 "~/.emacs.d/straight/repos/orderless/orderless.el" "odrless")
(112 23 28 30 31 32 33 34)

(flx-rs-score
 "Code/Everyone/Xamarin/EMJavaBindings/EMJavaBindings/Additions/DrawableSoftReference.cs"
 "odrless")
(180 1 62 63 68 69 70 85)

**Comment by jcs090218** [comment]
Thanks for the test; I will look into it once I have time! :)

**Comment by jcs090218** [comment]
This should be fix in #7.
